export const lcsData = [
  { id: 'AMPT', value: 'Ameerpet', defaultValue: null },
  { id: 'DLSNR', value: 'Dilshuknagar', defaultValue: null },
  { id: 'HITCH', value: 'Hitech city', defaultValue: null },
  { id: 'MDHPR', value: 'Madhapur', defaultValue: null },
];

export const pcsData = [
  {
    fid: '1',
    facilityCode: 'PMS1000',
    facilityName: 'Sai Hostels',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: 'Female',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1000',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1000',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1000',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1000',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1000',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1000',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1000',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '3',
    facilityCode: 'PMS1001',
    facilityName: 'Sri Laxmi Hostels',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '6500',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: 'Female',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1001',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1001',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1001',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1001',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1001',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1001',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '4',
    facilityCode: 'PMS1002',
    facilityName: 'Ganesh boys Hostels',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: 'Male',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1002',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1002',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1002',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1002',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1002',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1002',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1002',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '5',
    facilityCode: 'PMS1003',
    facilityName: 'Babu boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1003',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1003',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1003',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1003',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1003',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1003',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1003',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '6',
    facilityCode: 'PMS1004',
    facilityName: 'Kiran boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5500',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1004',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1004',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1004',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1004',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1004',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1004',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '7',
    facilityCode: 'PMS1005',
    facilityName: 'Ramu boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1005',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1005',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1005',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1005',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1005',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1005',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1005',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '8',
    facilityCode: 'PMS1006',
    facilityName: 'Ramesh boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1006',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1006',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1006',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1006',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1006',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1006',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
    ],
  },
  {
    fid: '9',
    facilityCode: 'PMS1007',
    facilityName: 'Sowya boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1007',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1007',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1007',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1007',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1007',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1007',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1007',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '10',
    facilityCode: 'PMS1008',
    facilityName: 'Raja boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1008',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1008',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1008',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1008',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1008',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1008',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '11',
    facilityCode: 'PMS1009',
    facilityName: 'Santhosh boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '6000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1009',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1009',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1009',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1009',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1009',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1009',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
    ],
  },
  {
    fid: '12',
    facilityCode: 'PMS1010',
    facilityName: 'Nirmala boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1010',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1010',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1010',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1010',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1010',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1010',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1010',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '13',
    facilityCode: 'PMS1011',
    facilityName: 'Madhu boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1011',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1011',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1011',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1011',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1011',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1011',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1011',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '14',
    facilityCode: 'PMS1012',
    facilityName: 'Navya boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '4500',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1012',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1012',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1012',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1012',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1012',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1012',
        unitType: 'Double Occupancy',
        unitRent: '8000',
        occupied: 10,
        available: 2,
      },
      {
        facilityCode: 'PMS1012',
        unitType: 'Single Occupancy',
        unitRent: '5000',
        occupied: 5,
        available: 3,
      },
    ],
  },
  {
    fid: '15',
    facilityCode: 'PMS1013',
    facilityName: 'Murali boys hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1013',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1013',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1013',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1013',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1013',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1013',
        unitType: 'Double Occupancy',
        unitRent: '9000',
        occupied: 10,
        available: 8,
      },
      {
        facilityCode: 'PMS1013',
        unitType: 'Single Occupancy',
        unitRent: '6000',
        occupied: 10,
        available: 8,
      },
    ],
  },
  {
    fid: '16',
    facilityCode: 'PMS1014',
    facilityName: 'Sai Priya Girls Hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '5000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1014',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1014',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1014',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1014',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1014',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1014',
        unitType: 'Double Occupancy',
        unitRent: '9000',
        occupied: 10,
        available: 8,
      },
      {
        facilityCode: 'PMS1014',
        unitType: 'Single Occupancy',
        unitRent: '6000',
        occupied: 10,
        available: 8,
      },
    ],
  },
  {
    fid: '17',
    facilityCode: 'PMS1015',
    facilityName: 'Ramya Girls Hostel',
    title: '',
    details: '',
    cityCode: 'Hyd',
    locationCode: 'AMPT',
    addressLine1: '',
    addressLine2: '',
    pincode: '',
    rentMonthly: '6000',
    advanceMonths: '1',
    rentIncludeGST: 'True',
    occupancy: '20',
    available: '10',
    gender: '',
    mapUrl: 'https://www.google.com/maps/@17.4370299,78.4410784,15z',
    longitude: '17.4370299',
    latitude: '78.4410784',
    facilityAmenities: [
      {
        facilityCode: 'PMS1015',
        amenityNames: 'Attached Balcony,Attached Washroom,Storage Shelf,Shared Washroom,Window',
      },
    ],
    facilityServices: [
      {
        facilityCode: 'PMS1015',
        serviceNames: 'High-Speed WIFI,Hot Water Supply,Power Backup,Professional Housekeeping,Workout Zone',
      },
    ],
    listOfFacilityImages: [
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+1.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+2.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+3.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+4.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+5.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+6.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+7.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+8.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+9.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+10.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+11.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+12.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+13.jpg',
        isFeature: false,
      },
      {
        facilityCode: 'PMS1015',
        photoURL: 'https://crisprgreentrack.s3.us-east-2.amazonaws.com/PMS+Website/PG+14.jpg',
        isFeature: false,
      },
    ],
    listOfFacilityVideos: null,
    listOfFoodItems: [
      {
        facilityCode: 'PMS1015',
        day: 'Monday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Tuesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Wednesday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Thursday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Friday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Saturday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
      {
        facilityCode: 'PMS1015',
        day: 'Sunday',
        breakfast: 'Dosa',
        lunch: 'Rice,Rasam,Curd',
        dinner: 'Rice,Rasam,Curd',
      },
    ],
    listOfUnitTypes: [
      {
        facilityCode: 'PMS1015',
        unitType: 'Double Occupancy',
        unitRent: '9000',
        occupied: 10,
        available: 8,
      },
      {
        facilityCode: 'PMS1015',
        unitType: 'Single Occupancy',
        unitRent: '6000',
        occupied: 10,
        available: 8,
      },
    ],
  },
];
